package vu.psk1lab.mybatis.model;

import java.util.List;

public class Pilot {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PILOT.ID
     *
     * @mbg.generated Wed May 04 14:54:36 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PILOT.AIRLINE
     *
     * @mbg.generated Wed May 04 14:54:36 EEST 2022
     */
    private String airline;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PILOT.PILOT_NAME
     *
     * @mbg.generated Wed May 04 14:54:36 EEST 2022
     */
    private String pilotName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PILOT.AIRLINES_ID
     *
     * @mbg.generated Wed May 04 14:54:36 EEST 2022
     */
    private Integer airlinesId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PILOT.ID
     *
     * @return the value of PUBLIC.PILOT.ID
     *
     * @mbg.generated Wed May 04 14:54:36 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PILOT.ID
     *
     * @param id the value for PUBLIC.PILOT.ID
     *
     * @mbg.generated Wed May 04 14:54:36 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PILOT.AIRLINE
     *
     * @return the value of PUBLIC.PILOT.AIRLINE
     *
     * @mbg.generated Wed May 04 14:54:36 EEST 2022
     */
    public String getAirline() {
        return airline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PILOT.AIRLINE
     *
     * @param airline the value for PUBLIC.PILOT.AIRLINE
     *
     * @mbg.generated Wed May 04 14:54:36 EEST 2022
     */
    public void setAirline(String airline) {
        this.airline = airline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PILOT.PILOT_NAME
     *
     * @return the value of PUBLIC.PILOT.PILOT_NAME
     *
     * @mbg.generated Wed May 04 14:54:36 EEST 2022
     */
    public String getPilotName() {
        return pilotName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PILOT.PILOT_NAME
     *
     * @param pilotName the value for PUBLIC.PILOT.PILOT_NAME
     *
     * @mbg.generated Wed May 04 14:54:36 EEST 2022
     */
    public void setPilotName(String pilotName) {
        this.pilotName = pilotName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PILOT.AIRLINES_ID
     *
     * @return the value of PUBLIC.PILOT.AIRLINES_ID
     *
     * @mbg.generated Wed May 04 14:54:36 EEST 2022
     */
    public Integer getAirlinesId() {
        return airlinesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PILOT.AIRLINES_ID
     *
     * @param airlinesId the value for PUBLIC.PILOT.AIRLINES_ID
     *
     * @mbg.generated Wed May 04 14:54:36 EEST 2022
     */
    public void setAirlinesId(Integer airlinesId) {
        this.airlinesId = airlinesId;
    }

    private Airline airlines;

    private List<Plane> planeList;


}