package vu.psk1lab.mybatis.model;

import java.util.List;

public class Plane {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PLANE.ID
     *
     * @mbg.generated Wed May 04 14:54:36 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PLANE.PILOT
     *
     * @mbg.generated Wed May 04 14:54:36 EEST 2022
     */
    private Integer pilot;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PLANE.PLANE_NO
     *
     * @mbg.generated Wed May 04 14:54:36 EEST 2022
     */
    private String planeNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PLANE.AIRLINE_ID
     *
     * @mbg.generated Wed May 04 14:54:36 EEST 2022
     */
    private Integer airlineId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PLANE.ID
     *
     * @return the value of PUBLIC.PLANE.ID
     *
     * @mbg.generated Wed May 04 14:54:36 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PLANE.ID
     *
     * @param id the value for PUBLIC.PLANE.ID
     *
     * @mbg.generated Wed May 04 14:54:36 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PLANE.PILOT
     *
     * @return the value of PUBLIC.PLANE.PILOT
     *
     * @mbg.generated Wed May 04 14:54:36 EEST 2022
     */
    public Integer getPilot() {
        return pilot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PLANE.PILOT
     *
     * @param pilot the value for PUBLIC.PLANE.PILOT
     *
     * @mbg.generated Wed May 04 14:54:36 EEST 2022
     */
    public void setPilot(Integer pilot) {
        this.pilot = pilot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PLANE.PLANE_NO
     *
     * @return the value of PUBLIC.PLANE.PLANE_NO
     *
     * @mbg.generated Wed May 04 14:54:36 EEST 2022
     */
    public String getPlaneNo() {
        return planeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PLANE.PLANE_NO
     *
     * @param planeNo the value for PUBLIC.PLANE.PLANE_NO
     *
     * @mbg.generated Wed May 04 14:54:36 EEST 2022
     */
    public void setPlaneNo(String planeNo) {
        this.planeNo = planeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PLANE.AIRLINE_ID
     *
     * @return the value of PUBLIC.PLANE.AIRLINE_ID
     *
     * @mbg.generated Wed May 04 14:54:36 EEST 2022
     */
    public Integer getAirlineId() {
        return airlineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PLANE.AIRLINE_ID
     *
     * @param airlineId the value for PUBLIC.PLANE.AIRLINE_ID
     *
     * @mbg.generated Wed May 04 14:54:36 EEST 2022
     */
    public void setAirlineId(Integer airlineId) {
        this.airlineId = airlineId;
    }

    private Airline airline;

    private List<Pilot> pilotList;
}