package vu.psk1lab.mybatis.dao;

import java.util.List;

import org.mybatis.cdi.Mapper;
import vu.psk1lab.mybatis.model.Airline;
import vu.psk1lab.mybatis.model.Pilot;
import vu.psk1lab.mybatis.model.Plane;

@Mapper
public interface AirlineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.AIRLINE
     *
     * @mbg.generated Wed May 04 14:54:36 EEST 2022
     */
    int deleteByPrimaryKey(Integer airlineId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.AIRLINE
     *
     * @mbg.generated Wed May 04 14:54:36 EEST 2022
     */
    int insert(Airline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.AIRLINE
     *
     * @mbg.generated Wed May 04 14:54:36 EEST 2022
     */
    Airline selectByPrimaryKey(Integer airlineId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.AIRLINE
     *
     * @mbg.generated Wed May 04 14:54:36 EEST 2022
     */
    List<Airline> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.AIRLINE
     *
     * @mbg.generated Wed May 04 14:54:36 EEST 2022
     */
    int updateByPrimaryKey(Airline record);

    List<Pilot> selectPilotsForAirline(Integer id);

    List<Plane> selectPlanesForAirline(Integer id);


}