package vu.psk1lab.mybatis.dao;

import java.util.List;

import org.mybatis.cdi.Mapper;
import vu.psk1lab.mybatis.model.Airline;
import vu.psk1lab.mybatis.model.Pilot;
import vu.psk1lab.mybatis.model.Plane;

@Mapper
public interface PilotMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PILOT
     *
     * @mbg.generated Wed May 04 14:54:36 EEST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PILOT
     *
     * @mbg.generated Wed May 04 14:54:36 EEST 2022
     */
    int insert(Pilot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PILOT
     *
     * @mbg.generated Wed May 04 14:54:36 EEST 2022
     */
    Pilot selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PILOT
     *
     * @mbg.generated Wed May 04 14:54:36 EEST 2022
     */
    List<Pilot> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PILOT
     *
     * @mbg.generated Wed May 04 14:54:36 EEST 2022
     */
    int updateByPrimaryKey(Pilot record);

    Airline getPilotAirlines(Integer id);


    List<Plane> selectPlanesForPilots(Integer id);

}